### ISSUE TITLE
No way to detect failed logins in app

### ISSUE THREAD

**Issue by karakayasemi** [owncloud/security#1]
I am struggling with detect failed login in app. Firstly, I thought I can add Middleware to loginController. Afterward, I understood that only I can add middleware to app controllers. No way to access failed login attempts with app middleware without modifying the source code. 
I tried to check the password in the application with a preLogin hook. However, there is an error in the logic of emitting preLogin signal in the LoginController. UserSession's login function is checking password and emitting preLogin signal, but loginController is either checking password before UserSession and returning response without hook signal when failed login attempts.
Only way I can find to detect failed login is the log file. Maybe I can read log file with a cronjob, but it is not a proper way.

**Comment by DeepDiver1975** [comment]
Please change the core login controller in a way so that a middleware can be injected.

THX

**Comment by karakayasemi** [comment]
I will try to make the login controller, middleware injectable. Should I register my app's middleware from /AppFramework/DependencyInjection/DIContainer.php? I can check security app is enabled or not, if it enabled I can register middleware. Is there any better approach?

If we use login hooks, I can also make a PR to move login signal emitting logic from UserSession to loginController.

**Comment by DeepDiver1975** [comment]
I guess we can close this ....
