### ISSUE TITLE
we need to find a different approach for the sleep operatoin ...

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/security#12]
using sleep on the server side will not only block the user but also block the whole server infrastructure.

this could lead to a denial of service

@Peter-Prochaska what would be an appropriate solution here? THX

**Comment by karakayasemi** [comment]
Maybe we can check login attempts ip in preLogin, and if his attempts bigger than certain threshold we can directly return a ban response.

**Comment by DeepDiver1975** [comment]
wana give it a try?

**Comment by karakayasemi** [comment]
I am on it now.

**Comment by karakayasemi** [comment]
We can use samething for 404s
