### ISSUE TITLE
what is the true way to block an ip?

### ISSUE THREAD

**Issue by karakayasemi** [owncloud/security#20]
We should block an ip, which has got too many 404 errors. How should we do that? I will try throwing an exception with preSetup callback. Any other suggestions?

**Comment by DeepDiver1975** [comment]
in base.php there is one pretty early event emitted:

```php
		\OC::$server->getEventLogger()->start('init_session', 'Initialize session');

**Comment by karakayasemi** [comment]
Is it enough to throw an error in the listener? I will look at it.

**Comment by DeepDiver1975** [comment]
> Is it enough to throw an error in the listener? I will look at it.

it depends on the execption type - afaik HintExceptions are the ones to use
