### ISSUE TITLE
Unable to go to settings page after install 

### ISSUE THREAD

**Issue by Kawohl** [owncloud/security#23]
Steps to reproduce:

1.Have ownCloud 10.0.3 installed.
2. Install security app from market an then go to settings in the browser.
3. Browser has this output:

template:settings-personal
File: /var/www/owncloud/lib/private/Template/TemplateFileLocator.php
Line: 55

Trace

#0 /var/www/owncloud/lib/private/legacy/template.php(199): OC\Template\TemplateFileLocator->find('settings-person...')
#1 /var/www/owncloud/lib/private/legacy/template.php(88): OC_Template->findTemplate(Object(OC\Theme\Theme), 'security', 'settings-person...')
#2 /var/www/owncloud/apps/security/lib/Panels/PersonalPanel.php(37): OC_Template->__construct('security', 'settings-person...')
#3 /var/www/owncloud/settings/Controller/SettingsPageController.php(142): OCA\Security\Panels\PersonalPanel->getPanel()
#4 /var/www/owncloud/settings/Controller/SettingsPageController.php(85): OC\Settings\Controller\SettingsPageController->getPanelsData(Array)
#5 [internal function]: OC\Settings\Controller\SettingsPageController->getPersonal('general')
#6 /var/www/owncloud/lib/private/AppFramework/Http/Dispatcher.php(159): call_user_func_array(Array, Array)
#7 /var/www/owncloud/lib/private/AppFramework/Http/Dispatcher.php(89): OC\AppFramework\Http\Dispatcher->executeController(Object(OC\Settings\Controller\SettingsPageController), 'getPersonal')
#8 /var/www/owncloud/lib/private/AppFramework/App.php(98): OC\AppFramework\Http\Dispatcher->dispatch(Object(OC\Settings\Controller\SettingsPageController), 'getPersonal')
#9 /var/www/owncloud/lib/private/AppFramework/Routing/RouteActionHandler.php(46): OC\AppFramework\App::main('SettingsPageCon...', 'getPersonal', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
#10 [internal function]: OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
#11 /var/www/owncloud/lib/private/Route/Router.php(307): call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
#12 /var/www/owncloud/lib/base.php(928): OC\Route\Router->match('/settings/perso...')
#13 /var/www/owncloud/index.php(56): OC::handleRequest()
#14 {main}

My first guess would be: I installed the enterprise bundle for testing purposes and removed it, however the enterprise theme is still activated.

**Comment by DeepDiver1975** [comment]
maybe more an issue with the theme template handling then.

does it happen on a clean oc installation?

**Comment by karakayasemi** [comment]
The makefile does not package templates. I will rebuild it

**Comment by karakayasemi** [comment]
@Kawohl please test, version 0.0.2 from the marketplace, I believe it will work this time, thanks.

**Comment by Kawohl** [comment]
great job and thanks for the quick fix! Can confirm UI works now!
