### ISSUE TITLE
Add Whitelist feature

### ISSUE THREAD

**Issue by ITMaya** [owncloud/security#26]
Hello,

That would be wonderful to be able to add IP to a Whitelist, not to block ourselves from Owncloud :)

Thanks for your work.
Regards,
John.

**Comment by karakayasemi** [comment]
In my POV,  it is reasonable. I will implement it as soon as possible.

**Comment by ITMaya** [comment]
Great, thank you!

**Comment by fretscha** [comment]
Hi, I would also appreciate a IP whitelist to avoid  DOS  for known networks.

**Comment by karakayasemi** [comment]
There will be no further development of this repository. I moved this issue to brute-force protection repo: https://github.com/owncloud/brute_force_protection/issues/15
