### ISSUE TITLE
code does not follow the ownCloud coding style guide

### ISSUE THREAD

**Issue by individual-it** [owncloud/security#30]
The ownCloud coding style guide is described here: https://doc.owncloud.org/server/10.0/developer_manual/general/codingguidelines.html#php
and can easily checked with phpcs. Here the output of the current master branch: 
[phpcs-output-security-app.txt](https://github.com/owncloud/security/files/1611215/phpcs-output-security-app.txt)

**Comment by karakayasemi** [comment]
There will be no further development of this repository. Introduced php-cs-fixer policies for brute-force protection app in here: owncloud/brute_force_protection#11
