### ISSUE TITLE
Update the Password Enforcement Policy

### ISSUE THREAD

**Issue by mdisrail2468** [owncloud/security#34]
Hell Team,

You are validating the 4 things right now but missing some important policies. Here are some policy which will improve the security of your webapp.

(01) Set the maximum character length for a password as a best practice e.g. thirty characters max.
(02) No spaces.
(03) No consecutive keyboard characters.
(04) No consecutive identical characters.

Please find this article for reference: https://eits.uga.edu/access_and_security/infosec/pols_regs/policies/passwords/password_standard/

Hope to hear back some positive news from your side.

Regards & Thanks 
Mohammed Israil

**Comment by DeepDiver1975** [comment]
> (01) Set the maximum character length for a password as a best practice e.g. thirty characters max.

I don't think a maximum character limit will help anything. There is a minimum and if someone wants to use more -> go ahead



> (02) No spaces.

I think this already applies - but worth a test. THX



> (03) No consecutive keyboard characters.
> (04) No consecutive identical characters.

Valid - pull requests are welcome ;-)

**Comment by mdisrail2468** [comment]
Hello,

I do agree that setting a maximum password length for a password will not anything directly but what if someone just copies and pastes the Holy Bible multiple times there and for sure it will consume more space at the database. I don't know if there's a validation at the backend but some sort of validation on the frontend also matters a lot.

And for the 3rd and 4th proposal I'll surely create a pull request.

**Comment by DeepDiver1975** [comment]
> but what if someone just copies and pastes the Holy Bible multiple times there and for sure it will consume more space at the database.

since one never stores clear text password but only hashes there is no issue ...

**Comment by karakayasemi** [comment]
@DeepDiver1975 will we separate password_policy features from this application?  #32 waiting for this decision. if https://github.com/owncloud/password_policy will be released as community app, we have already brute-force only version of this app in here https://github.com/owncloud/security/pull/32#issuecomment-367508559

**Comment by DeepDiver1975** [comment]
Oh - yes @karakayasemi you are right - thx for the hint

@mdisrail2468 I'm closing this in here

**Comment by karakayasemi** [comment]
@mdisrail2468 feel free to open issue/pull request on https://github.com/owncloud/password_policy. Thanks.
