### ISSUE TITLE
Extract brute-force feature into separate app, deprecate in favor of password-policy

### ISSUE THREAD

**Issue by PVince81** [owncloud/security#35]
The upcoming [password policy app](https://github.com/owncloud/password_policy) will have features that are redundant in the security app, and also bring a few more like password expiration.
If we'd remove the password policy part of the security app, the app would only be about brute-force protection.

Instead, here is a proposed plan:
1) Copy the brute-force protection feature into a new app "Brute-Force Protection"
2) Re-release a new version of "security" app to deprecate it with max-version=10.0.8 and a message telling admins to install both the [password policy app](https://github.com/owncloud/password_policy) and also the brute force app to keep the same functionality.

The reason for this is to provide a smoother upgrade path and have the possibility to release the security app again in parallel to brute force during the migration period.

@karakayasemi @DeepDiver1975 @pmaier1

**Comment by karakayasemi** [comment]
Sounds good, I will release a final version for this app when I find a time. Where should I add "will be deprecated" message in the app? 
Thanks to @mdusher, we have already a branch in here https://github.com/AARNet/security/tree/bruteforceonly with only brute force protection feature. We can release both brute force protection app and password_policy app together.

**Comment by PVince81** [comment]
@karakayasemi for the deprecation message I suggest the following:
- add in info.xml description
- add in marketplace description (unless it's already derived from the info.xml)
- add a banner new the security app settings in the settings page, not sure if useful though

**Comment by pmaier1** [comment]
After talking to @PVince81 "max-version" of the deprecation release of the 'Security' app should be set to "10.0.8" to avoid interference with the new "Password Policy' app which has max-version=10.0.9. Changed in OP as well.

**Comment by PVince81** [comment]
- [x] security app deprecation https://github.com/owncloud/security/pull/37
- [ ] brute force app repo + code
- [ ] password policy app 2.0.0 release: https://github.com/owncloud/password_policy/issues/17
- [ ] brute force app release
- [ ] security app release

let's release the security app with the warning as the last step

**Comment by PVince81** [comment]
@karakayasemi I've created a new repo for the app, please push the code there

**Comment by karakayasemi** [comment]
@PVince81 I refactored current security app and adapted for brute force app. But, I messed up something in the brute force repo when importing. Could you delete then recreate repo or change default branch to master when you make time?

**Comment by PVince81** [comment]
@karakayasemi ok I've recreated the repo, this time with GPLv3 license in it, as I saw this was what you had: https://github.com/owncloud/brute_force_protection

**Comment by karakayasemi** [comment]
@PVince81 thank you, perfect :)

**Comment by karakayasemi** [comment]
Final release v.0.0.3 ready in the marketplace : https://marketplace.owncloud.com/apps/security
