### ISSUE TITLE
Table oc_failed_login_attempts is not compatible with MariaDB Galera Cluster.

### ISSUE THREAD

**Issue by GrimDemon** [owncloud/security#38]
This table doesn't have PRIMARY or UNIQUE key and automatic records removal doesn't work for it in Galera environment. Creating UNIQUE index for all colums doens't make any difference. For example I have default values for blocking login attempts (600/3/300), but in DB I have records from a few days ago. The records stays there until I truncate them.

**Comment by karakayasemi** [comment]
We can add a background job and occ command to remove old failed login attempt entries. It sounds logical to me.

By the way, this app will be deprecated soon and its functionalities will be separated into two different apps: password_policy and brute_force_protection apps. 

I am currently, moving the current code base of brute force protection into this repo; https://github.com/owncloud/brute_force_protection. I raised a ticket for your issue in the new repo: https://github.com/owncloud/brute_force_protection/issues/2. We can discuss the details in the new issue. I am closing this in here.

**Comment by GrimDemon** [comment]
Thx for this information 👍
