### ISSUE TITLE
how is the banned entered

### ISSUE THREAD

**Issue by soydepr** [owncloud/security#39]
this is a question , how is the banned executed?  iptables?

**Comment by karakayasemi** [comment]
The app listens failedLogin and preLogin hooks. In the failed login callback, it saves failed login attempts. In the preLogin callback, it blocks uid+up combination after certain failed login attempt in the determined period by throwing login exception. See here  https://github.com/owncloud/security/blob/master/lib/Throttle.php#L88. If you have further question, you can reopen this ticket or create a topic in the central.owncloud.org
