### ISSUE TITLE
Properly handle passowrd policy error in user mgmt

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/security#9]
![bildschirmfoto von 2017-08-16 10-30-54](https://user-images.githubusercontent.com/1005065/29354500-0d38327c-826e-11e7-8226-ad887f117619.png)

**Comment by karakayasemi** [comment]
@DeepDiver1975 What is the problem in here? I want to prepare the app for the marketplace after resolving existing issues.
![image](https://user-images.githubusercontent.com/14157973/31886341-93527ae8-b7fc-11e7-8f27-4228861c91de.png)

**Comment by karakayasemi** [comment]
Password policy will not be part of this app. closing this.
